// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: message.proto

package Distribuidos3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerRasputinClient is the client API for BrokerRasputin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerRasputinClient interface {
	AgregarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error)
	RenombrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error)
	ActualizarValor(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error)
	BorrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error)
	GetSoldados(ctx context.Context, in *DatosBase, opts ...grpc.CallOption) (*SoldadosBase, error)
}

type brokerRasputinClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerRasputinClient(cc grpc.ClientConnInterface) BrokerRasputinClient {
	return &brokerRasputinClient{cc}
}

func (c *brokerRasputinClient) AgregarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error) {
	out := new(Direccion)
	err := c.cc.Invoke(ctx, "/grpc.BrokerRasputin/AgregarBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerRasputinClient) RenombrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error) {
	out := new(Direccion)
	err := c.cc.Invoke(ctx, "/grpc.BrokerRasputin/RenombrarBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerRasputinClient) ActualizarValor(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error) {
	out := new(Direccion)
	err := c.cc.Invoke(ctx, "/grpc.BrokerRasputin/ActualizarValor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerRasputinClient) BorrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Direccion, error) {
	out := new(Direccion)
	err := c.cc.Invoke(ctx, "/grpc.BrokerRasputin/BorrarBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerRasputinClient) GetSoldados(ctx context.Context, in *DatosBase, opts ...grpc.CallOption) (*SoldadosBase, error) {
	out := new(SoldadosBase)
	err := c.cc.Invoke(ctx, "/grpc.BrokerRasputin/GetSoldados", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerRasputinServer is the server API for BrokerRasputin service.
// All implementations must embed UnimplementedBrokerRasputinServer
// for forward compatibility
type BrokerRasputinServer interface {
	AgregarBase(context.Context, *Peticion) (*Direccion, error)
	RenombrarBase(context.Context, *Peticion) (*Direccion, error)
	ActualizarValor(context.Context, *Peticion) (*Direccion, error)
	BorrarBase(context.Context, *Peticion) (*Direccion, error)
	GetSoldados(context.Context, *DatosBase) (*SoldadosBase, error)
	mustEmbedUnimplementedBrokerRasputinServer()
}

// UnimplementedBrokerRasputinServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerRasputinServer struct {
}

func (UnimplementedBrokerRasputinServer) AgregarBase(context.Context, *Peticion) (*Direccion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgregarBase not implemented")
}
func (UnimplementedBrokerRasputinServer) RenombrarBase(context.Context, *Peticion) (*Direccion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenombrarBase not implemented")
}
func (UnimplementedBrokerRasputinServer) ActualizarValor(context.Context, *Peticion) (*Direccion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActualizarValor not implemented")
}
func (UnimplementedBrokerRasputinServer) BorrarBase(context.Context, *Peticion) (*Direccion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrarBase not implemented")
}
func (UnimplementedBrokerRasputinServer) GetSoldados(context.Context, *DatosBase) (*SoldadosBase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSoldados not implemented")
}
func (UnimplementedBrokerRasputinServer) mustEmbedUnimplementedBrokerRasputinServer() {}

// UnsafeBrokerRasputinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerRasputinServer will
// result in compilation errors.
type UnsafeBrokerRasputinServer interface {
	mustEmbedUnimplementedBrokerRasputinServer()
}

func RegisterBrokerRasputinServer(s grpc.ServiceRegistrar, srv BrokerRasputinServer) {
	s.RegisterService(&BrokerRasputin_ServiceDesc, srv)
}

func _BrokerRasputin_AgregarBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerRasputinServer).AgregarBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerRasputin/AgregarBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerRasputinServer).AgregarBase(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerRasputin_RenombrarBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerRasputinServer).RenombrarBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerRasputin/RenombrarBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerRasputinServer).RenombrarBase(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerRasputin_ActualizarValor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerRasputinServer).ActualizarValor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerRasputin/ActualizarValor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerRasputinServer).ActualizarValor(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerRasputin_BorrarBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerRasputinServer).BorrarBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerRasputin/BorrarBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerRasputinServer).BorrarBase(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerRasputin_GetSoldados_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatosBase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerRasputinServer).GetSoldados(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerRasputin/GetSoldados",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerRasputinServer).GetSoldados(ctx, req.(*DatosBase))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerRasputin_ServiceDesc is the grpc.ServiceDesc for BrokerRasputin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerRasputin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.BrokerRasputin",
	HandlerType: (*BrokerRasputinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgregarBase",
			Handler:    _BrokerRasputin_AgregarBase_Handler,
		},
		{
			MethodName: "RenombrarBase",
			Handler:    _BrokerRasputin_RenombrarBase_Handler,
		},
		{
			MethodName: "ActualizarValor",
			Handler:    _BrokerRasputin_ActualizarValor_Handler,
		},
		{
			MethodName: "BorrarBase",
			Handler:    _BrokerRasputin_BorrarBase_Handler,
		},
		{
			MethodName: "GetSoldados",
			Handler:    _BrokerRasputin_GetSoldados_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// ServidorPlanetarioClient is the client API for ServidorPlanetario service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServidorPlanetarioClient interface {
	AgregarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error)
	RenombrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error)
	ActualizarValor(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error)
	BorrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error)
}

type servidorPlanetarioClient struct {
	cc grpc.ClientConnInterface
}

func NewServidorPlanetarioClient(cc grpc.ClientConnInterface) ServidorPlanetarioClient {
	return &servidorPlanetarioClient{cc}
}

func (c *servidorPlanetarioClient) AgregarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error) {
	out := new(Reloj)
	err := c.cc.Invoke(ctx, "/grpc.ServidorPlanetario/AgregarBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servidorPlanetarioClient) RenombrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error) {
	out := new(Reloj)
	err := c.cc.Invoke(ctx, "/grpc.ServidorPlanetario/RenombrarBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servidorPlanetarioClient) ActualizarValor(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error) {
	out := new(Reloj)
	err := c.cc.Invoke(ctx, "/grpc.ServidorPlanetario/ActualizarValor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servidorPlanetarioClient) BorrarBase(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Reloj, error) {
	out := new(Reloj)
	err := c.cc.Invoke(ctx, "/grpc.ServidorPlanetario/BorrarBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServidorPlanetarioServer is the server API for ServidorPlanetario service.
// All implementations must embed UnimplementedServidorPlanetarioServer
// for forward compatibility
type ServidorPlanetarioServer interface {
	AgregarBase(context.Context, *Peticion) (*Reloj, error)
	RenombrarBase(context.Context, *Peticion) (*Reloj, error)
	ActualizarValor(context.Context, *Peticion) (*Reloj, error)
	BorrarBase(context.Context, *Peticion) (*Reloj, error)
	mustEmbedUnimplementedServidorPlanetarioServer()
}

// UnimplementedServidorPlanetarioServer must be embedded to have forward compatible implementations.
type UnimplementedServidorPlanetarioServer struct {
}

func (UnimplementedServidorPlanetarioServer) AgregarBase(context.Context, *Peticion) (*Reloj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgregarBase not implemented")
}
func (UnimplementedServidorPlanetarioServer) RenombrarBase(context.Context, *Peticion) (*Reloj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenombrarBase not implemented")
}
func (UnimplementedServidorPlanetarioServer) ActualizarValor(context.Context, *Peticion) (*Reloj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActualizarValor not implemented")
}
func (UnimplementedServidorPlanetarioServer) BorrarBase(context.Context, *Peticion) (*Reloj, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrarBase not implemented")
}
func (UnimplementedServidorPlanetarioServer) mustEmbedUnimplementedServidorPlanetarioServer() {}

// UnsafeServidorPlanetarioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServidorPlanetarioServer will
// result in compilation errors.
type UnsafeServidorPlanetarioServer interface {
	mustEmbedUnimplementedServidorPlanetarioServer()
}

func RegisterServidorPlanetarioServer(s grpc.ServiceRegistrar, srv ServidorPlanetarioServer) {
	s.RegisterService(&ServidorPlanetario_ServiceDesc, srv)
}

func _ServidorPlanetario_AgregarBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServidorPlanetarioServer).AgregarBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServidorPlanetario/AgregarBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServidorPlanetarioServer).AgregarBase(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServidorPlanetario_RenombrarBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServidorPlanetarioServer).RenombrarBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServidorPlanetario/RenombrarBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServidorPlanetarioServer).RenombrarBase(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServidorPlanetario_ActualizarValor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServidorPlanetarioServer).ActualizarValor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServidorPlanetario/ActualizarValor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServidorPlanetarioServer).ActualizarValor(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServidorPlanetario_BorrarBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServidorPlanetarioServer).BorrarBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServidorPlanetario/BorrarBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServidorPlanetarioServer).BorrarBase(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

// ServidorPlanetario_ServiceDesc is the grpc.ServiceDesc for ServidorPlanetario service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServidorPlanetario_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ServidorPlanetario",
	HandlerType: (*ServidorPlanetarioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgregarBase",
			Handler:    _ServidorPlanetario_AgregarBase_Handler,
		},
		{
			MethodName: "RenombrarBase",
			Handler:    _ServidorPlanetario_RenombrarBase_Handler,
		},
		{
			MethodName: "ActualizarValor",
			Handler:    _ServidorPlanetario_ActualizarValor_Handler,
		},
		{
			MethodName: "BorrarBase",
			Handler:    _ServidorPlanetario_BorrarBase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
